default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: admin

development:
  <<: *default
  database: myarticles_development

test:
  <<: *default
  database: myarticles_development

production:
  <<: *default
  database: myarticles_development
